name: sync-secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.1.2
        with:
          SECRETS: |
            ^DOCKER_.*
          REPOSITORIES: |
            3beca/scheduler
            3beca/notifier
            3beca/mapper
            3beca/cep
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_NO_SCOPES }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
