name: sync-secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.0.0
        with:
          SECRETS: |
            ^DOCKER_.*
          REPOSITORIES: |
            scheduler
            notifier
            mapper
            cep
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRETS }}
