name: sync-secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.3.1
        with:
          SECRETS: |
            ^DOCKER_.*
            ^SSH_.*
          REPOSITORIES: |
            3beca/scheduler
            3beca/notifier
            3beca/mapper
            3beca/cep
            3beca/cep-ui
            3beca/duck-dox
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_SYNC_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
