name: sync-secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^DOCKER_.*
            ^SSH_.*
          REPOSITORIES: |
            3beca/scheduler
            3beca/notifier
            3beca/mapper
            3beca/cep
            3beca/cep-ui
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_SYNC_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }} 
          SSH_KEY: ${{ secrets.SSH_KEY }} 
